---
# Main Playbook - Install Nomad, Consul, and Fabio
# Supports single/multi-master setup with secure TLS communication

- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Install and configure Consul servers
  hosts: consul_servers
  become: true
  roles:
    - consul

- name: Install and configure Consul clients
  hosts: consul_clients
  become: true
  roles:
    - consul

- name: Install and configure Nomad servers
  hosts: nomad_servers
  become: true
  roles:
    - nomad

- name: Install and configure Nomad clients
  hosts: nomad_clients
  become: true
  roles:
    - nomad

- name: Install and configure Fabio load balancer
  hosts: fabio_nodes
  become: true
  roles:
    - fabio
