---
all:
  children:
    # Consul servers (can be single or multi-master)
    consul_servers:
      hosts:
        consul-server-1:
          ansible_host: 192.168.1.10
        # Uncomment for multi-master setup
        # consul-server-2:
        #   ansible_host: 192.168.1.11
        # consul-server-3:
        #   ansible_host: 192.168.1.12

    # Nomad servers (can be single or multi-master)
    nomad_servers:
      hosts:
        nomad-server-1:
          ansible_host: 192.168.1.10
        # Uncomment for multi-master setup
        # nomad-server-2:
        #   ansible_host: 192.168.1.11
        # nomad-server-3:
        #   ansible_host: 192.168.1.12

    # Container worker nodes (Docker driver)
    container_workers:
      hosts:
        container-worker-1:
          ansible_host: 192.168.1.20
        # container-worker-2:
        #   ansible_host: 192.168.1.21

    # Systemd worker nodes (exec, raw_exec drivers)
    systemd_workers:
      hosts:
        systemd-worker-1:
          ansible_host: 192.168.1.30
        # systemd-worker-2:
        #   ansible_host: 192.168.1.31

    # Fabio load balancer nodes
    fabio_nodes:
      hosts:
        fabio-1:
          ansible_host: 192.168.1.40

    # Group all workers together
    nomad_clients:
      children:
        container_workers:
        systemd_workers:

    # Group all Consul clients (all nodes except Consul servers)
    consul_clients:
      children:
        nomad_clients:
        fabio_nodes:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
